apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterinfo
  labels:
    app: clusterinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterinfo
  template:
    metadata:
      labels:
        app: clusterinfo
    spec:
      containers:
      - name: clusterinfo
        image: scubakiz/clusterinfo:1.0.8
        ports:
        - containerPort: 80